/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javax.swing.*;
import org.scilab.forge.jlatexmath.*;
import classes.ecCuadraticas;
import classes.Complex;
import classes.Pair;
import classes.mathUtils;

/**
 * Clase que representa la interfaz gráfica del solucionador de ecuaciones diferenciales
 * Demuestra AGREGACIÓN: esta clase contiene objetos de tipo ecCuadraticas, Complex y Pair
 * 
 * @author angel
 */
public class frmSolver extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmSolver.class.getName());
    
    // ============= AGREGACIÓN EXPLÍCITA =============
    // Esta clase contiene (agrega) objetos de otras clases
    private ecCuadraticas ecuacionActual;        // Agregación de ecCuadraticas
    private Pair<Complex, Complex> raicesActuales;  // Agregación de Pair<Complex, Complex>
    private Complex raizCompleja1;               // Agregación de Complex
    private Complex raizCompleja2;               // Agregación de Complex

    /**
     * Creates new form frmSolver
     * Inicializa los objetos agregados
     */
    public frmSolver() {
        initComponents();
        
        // Inicializar objetos agregados
        this.ecuacionActual = new ecCuadraticas();  // Objeto agregado
        this.raicesActuales = null;                  // Se inicializa cuando se resuelve
        this.raizCompleja1 = new Complex();          // Objeto agregado
        this.raizCompleja2 = new Complex();          // Objeto agregado
        
        panSolution.setEnabled(false);
        panSolution.setVisible(false);
        
        TeXFormula title=new TeXFormula("\\text{Solucion General:}");
        TeXIcon tittleIcon=title.createTeXIcon(TeXConstants.STYLE_DISPLAY, 20);
        lblSolTitle.setIcon(tittleIcon);
        
        TeXFormula y=new TeXFormula("y=0"),dy=new TeXFormula("y'+"),d2y=new TeXFormula("y''+");
        TeXIcon iconY=y.createTeXIcon(TeXConstants.STYLE_DISPLAY, 25),
                iconDy=dy.createTeXIcon(TeXConstants.STYLE_DISPLAY, 25),
                iconD2y=d2y.createTeXIcon(TeXConstants.STYLE_DISPLAY, 25);
        
        lblY.setIcon(iconY); lblDy.setIcon(iconDy); lblD2y.setIcon(iconD2y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtB = new javax.swing.JTextField();
        txtA = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        lblD2y = new javax.swing.JLabel();
        lblDy = new javax.swing.JLabel();
        lblY = new javax.swing.JLabel();
        btnSolve = new javax.swing.JButton();
        panSolution = new javax.swing.JPanel();
        lblSol = new javax.swing.JLabel();
        lblSolTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtB.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCActionPerformed(evt);
            }
        });

        btnSolve.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSolve.setText("Solve");
        btnSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolveActionPerformed(evt);
            }
        });

        panSolution.setEnabled(false);

        javax.swing.GroupLayout panSolutionLayout = new javax.swing.GroupLayout(panSolution);
        panSolution.setLayout(panSolutionLayout);
        panSolutionLayout.setHorizontalGroup(
            panSolutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSolutionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panSolutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSol, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSolTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panSolutionLayout.setVerticalGroup(
            panSolutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSolutionLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblSolTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSol, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese los coeficientes de la ecuación");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Solucionador de Ec. Diff. Lineal Homogénea de Segundo Orden");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(356, 356, 356))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(lblD2y, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblDy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblY, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnSolve))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(panSolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblD2y, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnSolve)))
                .addGap(18, 18, 18)
                .addComponent(panSolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCActionPerformed
        
    }//GEN-LAST:event_txtCActionPerformed

    private void btnSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolveActionPerformed
        String sa = txtA.getText().trim();
        String sb = txtB.getText().trim();
        String sc = txtC.getText().trim();

        if (sa.isEmpty() || sb.isEmpty() || sc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor llena todos los campos con números.");
            return;
        }

        try {
            int a = Integer.parseInt(sa);
            int b = Integer.parseInt(sb);
            int c = Integer.parseInt(sc);

            String yc;
    
            if(a != 0) {
                // USANDO AGREGACIÓN: Creamos y almacenamos objeto ecCuadraticas
                this.ecuacionActual = new ecCuadraticas(a, b, c);
                yc = secondOrderEc(this.ecuacionActual);
            }
            else if (b != 0) {
                // USANDO AGREGACIÓN: Creamos y almacenamos objeto ecCuadraticas
                this.ecuacionActual = new ecCuadraticas(b, c);
                yc = firstOrderEc(this.ecuacionActual);
            }
            else {
                JOptionPane.showMessageDialog(this, "La expresion \""+c+"y=0\" no es una ecuación differencial");
                return;
            }

            TeXFormula Yc = new TeXFormula(yc);
            TeXIcon iconYc = Yc.createTeXIcon(TeXConstants.STYLE_DISPLAY, 23);

            panSolution.setEnabled(true);
            panSolution.setVisible(true);
            lblSol.setIcon(iconYc);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Algún campo es invalido, solo puedes ingresar numeros enteros");
        }
        
    }//GEN-LAST:event_btnSolveActionPerformed

    // ============= MÉTODOS CON AGREGACIÓN EXPLÍCITA =============
    
    /**
     * Resuelve ecuación diferencial de primer orden
     * Demuestra AGREGACIÓN: recibe un objeto ecCuadraticas agregado
     * 
     * @param ec objeto ecCuadraticas agregado que contiene los coeficientes
     * @return String con la solución en formato LaTeX
     */
    private String firstOrderEc(ecCuadraticas ec) {
        // AGREGACIÓN: Usamos el objeto ec agregado
        return firstOrderEc(ec.getB(), ec.getC());
    }

    /**
     * Resuelve ecuación diferencial de primer orden
     * Versión sobrecargada que recibe parámetros primitivos
     * 
     * @param b coeficiente de y'
     * @param c coeficiente de y
     * @return String con la solución en formato LaTeX
     */
    private String firstOrderEc(int b, int c) {
        int gcd = mathUtils.gcd(b, c);
        b /= gcd; 
        c /= gcd;
        
        c=-c;
        // Normalización de signos
        if (b < 0) {
            b = -b;
            c = -c;
        }

        String strSol,y;

        if (b == 1 && c == 1) {
            strSol = "1";
        } 
        else if (c == 1) {
            strSol = "\\frac{1}{" + b + "}";
        } 
        else if (b == 1) {
            strSol =  c + "";
        } 
        else {
            strSol = "\\frac{" + c + "}{" + b + "}";
        }
        
        if("1".equals(strSol)) strSol="";
        if("-1".equals(strSol)) strSol="-";
        
        y="Y_c=Ce^{"+strSol+"x}";

        return y;
    }

    /**
     * Resuelve ecuación diferencial de segundo orden
     * Demuestra AGREGACIÓN: recibe un objeto ecCuadraticas agregado
     * 
     * @param ec objeto ecCuadraticas agregado que contiene los coeficientes
     * @return String con la solución en formato LaTeX
     */
    private String secondOrderEc(ecCuadraticas ec) {
        // AGREGACIÓN: Usamos el objeto ec agregado
        return secondOrderEc(ec.getA(), ec.getB(), ec.getC());
    }

    /**
     * Resuelve ecuación diferencial de segundo orden
     * Versión sobrecargada que recibe parámetros primitivos
     * Demuestra AGREGACIÓN: crea y utiliza objetos Pair<Complex, Complex>
     * 
     * @param a coeficiente de y''
     * @param b coeficiente de y'
     * @param c coeficiente de y
     * @return String con la solución en formato LaTeX
     */
    private String secondOrderEc(int a, int b, int c){
        // AGREGACIÓN: Creamos objeto ecCuadraticas
        ecCuadraticas ecCaracteristica = new ecCuadraticas(a, b, c);
        
        // AGREGACIÓN: Obtenemos objeto Pair<Complex, Complex> agregado
        Pair<Complex, Complex> roots = ecCaracteristica.getRoots();
        this.raicesActuales = roots;  // Almacenamos las raíces agregadas
        
        // AGREGACIÓN: Obtenemos objetos Complex agregados del Pair
        this.raizCompleja1 = roots.getFirst();
        this.raizCompleja2 = roots.getSecond();
        
        int disc = ecCaracteristica.discriminante();
    
        String alpha,beta,alpha2;
        alpha = this.raizCompleja1.getAlpha(); 
        beta = this.raizCompleja1.getBeta();
        alpha2 = this.raizCompleja2.getAlpha(); 
        
        if("1".equals(alpha)) alpha="";
        if("-1".equals(alpha)) alpha="-";
        if("1".equals(beta)) beta="";
        if("-1".equals(beta)) beta="-";
        if("1".equals(alpha2)) alpha2="";
        if("-1".equals(alpha2)) alpha2="-";
        
        String y1,y2,yc;
        
        if(disc>0){
            if("0".equals(alpha))
                y1="";
            else
                y1="e^{"+alpha+"x}";
            if("0".equals(alpha2))
                y2="";
            else
                y2="e^{"+alpha2+"x}";
        }
        else if (disc==0){
            if("0".equals(alpha)){
                y1="";
                y2="x";
            }
            else {
            y1="e^{"+alpha+"x}";
            y2="x"+y1;
            }
        }
        else { // disc < 0
            
            if("0".equals(alpha)){
                y1="\\cos("+beta+"x)";
                y2="\\sin("+beta+"x)";
            }
            else {
                y1="e^{"+alpha+"x}\\cos("+beta+"x)";
                y2="e^{"+alpha+"x}\\sin("+beta+"x)";
            }
        }
        
        yc="Y_c = C_1"+y1+" + C_2"+y2;
        
        return yc;
    }
    
    // ============= GETTERS PARA ACCESO A OBJETOS AGREGADOS =============
    
    /**
     * Obtiene la ecuación actual agregada
     * @return objeto ecCuadraticas agregado
     */
    public ecCuadraticas getEcuacionActual() {
        return this.ecuacionActual;
    }
    
    /**
     * Obtiene las raíces actuales agregadas
     * @return objeto Pair<Complex, Complex> con las raíces
     */
    public Pair<Complex, Complex> getRaicesActuales() {
        return this.raicesActuales;
    }
    
    /**
     * Obtiene la primera raíz agregada
     * @return objeto Complex con la primera raíz
     */
    public Complex getRaizCompleja1() {
        return this.raizCompleja1;
    }
    
    /**
     * Obtiene la segunda raíz agregada
     * @return objeto Complex con la segunda raíz
     */
    public Complex getRaizCompleja2() {
        return this.raizCompleja2;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmSolver().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSolve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblD2y;
    private javax.swing.JLabel lblDy;
    private javax.swing.JLabel lblSol;
    private javax.swing.JLabel lblSolTitle;
    private javax.swing.JLabel lblY;
    private javax.swing.JPanel panSolution;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    // End of variables declaration//GEN-END:variables
}
