/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javax.swing.*;
import org.scilab.forge.jlatexmath.*;
import classes.ecCuadraticas;
import classes.Complex;
import classes.Pair;
import classes.mathUtils;

/**
 * Clase que representa la interfaz gráfica del solucionador de ecuaciones diferenciales
 * Demuestra AGREGACIÓN: esta clase contiene objetos de tipo ecCuadraticas, Complex y Pair
 * 
 * @author angel
 */
public class frmSolver extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmSolver.class.getName());
    
    // ============= AGREGACIÓN EXPLÍCITA =============
    // Esta clase contiene (agrega) objetos de otras clases
    private ecCuadraticas ecuacionActual;        // Agregación de ecCuadraticas
    private Pair<Complex, Complex> raicesActuales;  // Agregación de Pair<Complex, Complex>
    private Complex raizCompleja1;               // Agregación de Complex
    private Complex raizCompleja2;               // Agregación de Complex

    /**
     * Creates new form frmSolver
     * Inicializa los objetos agregados
     */
    public frmSolver() {
        initComponents();
        
        // Inicializar objetos agregados
        this.ecuacionActual = new ecCuadraticas();  // Objeto agregado
        this.raicesActuales = null;                  // Se inicializa cuando se resuelve
        this.raizCompleja1 = new Complex();          // Objeto agregado
        this.raizCompleja2 = new Complex();          // Objeto agregado
        
        panSolution.setEnabled(false);
        panSolution.setVisible(false);
        
        TeXFormula title=new TeXFormula("\\text{Solucion General:}");
        TeXIcon tittleIcon=title.createTeXIcon(TeXConstants.STYLE_DISPLAY, 20);
        lblSolTitle.setIcon(tittleIcon);
        
        TeXFormula y=new TeXFormula("y=0"),dy=new TeXFormula("y'+"),d2y=new TeXFormula("y''+");
        TeXIcon iconY=y.createTeXIcon(TeXConstants.STYLE_DISPLAY, 25),
                iconDy=dy.createTeXIcon(TeXConstants.STYLE_DISPLAY, 25),
                iconD2y=d2y.createTeXIcon(TeXConstants.STYLE_DISPLAY, 25);
        
        lblY.setIcon(iconY); lblDy.setIcon(iconDy); lblD2y.setIcon(iconD2y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtB = new javax.swing.JTextField();
        txtA = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        lblD2y = new javax.swing.JLabel();
        lblDy = new javax.swing.JLabel();
        lblY = new javax.swing.JLabel();
        btnSolve = new javax.swing.JButton();
        btnSteps = new javax.swing.JButton();
        panSolution = new javax.swing.JPanel();
        lblSol = new javax.swing.JLabel();
        lblSolTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtB.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtC.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSolve.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSolve.setText("Solve");
        btnSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolveActionPerformed(evt);
            }
        });

        btnSteps.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btnSteps.setText("Pasos");
        btnSteps.addActionListener(evt -> btnStepsActionPerformed(evt));

        panSolution.setEnabled(false);

        javax.swing.GroupLayout panSolutionLayout = new javax.swing.GroupLayout(panSolution);
        panSolution.setLayout(panSolutionLayout);
        panSolutionLayout.setHorizontalGroup(
            panSolutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSolutionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panSolutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSol, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSolTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panSolutionLayout.setVerticalGroup(
            panSolutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSolutionLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblSolTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSol, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese los coeficientes de la ecuación");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Solucionador de Ec. Diff. Lineal Homogénea de Segundo Orden");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(356, 356, 356))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(lblD2y, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblDy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblY, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnSolve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSteps))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(panSolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblD2y, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSolve)
                            .addComponent(btnSteps))))
                .addGap(18, 18, 18)
                .addComponent(panSolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolveActionPerformed
        String sa = txtA.getText().trim();
        String sb = txtB.getText().trim();
        String sc = txtC.getText().trim();

        if (sa.isEmpty() || sb.isEmpty() || sc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor llena todos los campos con números.");
            return;
        }

        try {
            int a = Integer.parseInt(sa);
            int b = Integer.parseInt(sb);
            int c = Integer.parseInt(sc);

            String yc;
    
            if(a != 0) {
                // USANDO AGREGACIÓN: Creamos y almacenamos objeto ecCuadraticas
                this.ecuacionActual = new ecCuadraticas(a, b, c);
                yc = secondOrderEc(this.ecuacionActual);
            }
            else if (b != 0) {
                // USANDO AGREGACIÓN: Creamos y almacenamos objeto ecCuadraticas
                this.ecuacionActual = new ecCuadraticas(b, c);
                yc = firstOrderEc(this.ecuacionActual);
            }
            else {
                JOptionPane.showMessageDialog(this, "La expresion \""+c+"y=0\" no es una ecuación differencial");
                return;
            }

            TeXFormula Yc = new TeXFormula(yc);
            TeXIcon iconYc = Yc.createTeXIcon(TeXConstants.STYLE_DISPLAY, 23);

            panSolution.setEnabled(true);
            panSolution.setVisible(true);
            lblSol.setIcon(iconYc);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Algún campo es invalido, solo puedes ingresar numeros enteros");
        }
        
    }//GEN-LAST:event_btnSolveActionPerformed

    private void btnStepsActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            StepData steps = buildSteps();
            frmSteps dlg = new frmSteps(steps.step1, steps.step2, steps.step3, steps.step4);
            dlg.setVisible(true);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    // Contenedor simple para los textos de pasos
    private static class StepData {
        String step1, step2, step3, step4;
    }

    // Construye los pasos a partir de los coeficientes en pantalla
    private StepData buildSteps() {
    String sa = txtA.getText().trim();
    String sb = txtB.getText().trim();
    String sc = txtC.getText().trim();
    if (sa.isEmpty() || sb.isEmpty() || sc.isEmpty()) {
        throw new IllegalArgumentException("Por favor llena todos los campos con números.");
    }

    int a, b, c;
    try {
        a = Integer.parseInt(sa);
        b = Integer.parseInt(sb);
        c = Integer.parseInt(sc);
    } catch (NumberFormatException e) {
        throw new IllegalArgumentException("Algún campo es inválido, solo números enteros.");
    }

    if (a == 0 && b == 0) {
        throw new IllegalArgumentException("a y b no pueden ser cero simultáneamente.");
    }

    // Calcula raíces con ecCuadraticas
    ecCuadraticas ec = (a != 0) ? new ecCuadraticas(a, b, c) : new ecCuadraticas(b, c);
    Pair<Complex, Complex> roots = (a != 0) ? ec.getRoots() : null;

    StepData sd = new StepData();

    // ===========================================================
    // 1) Ecuación característica
    // ===========================================================
    if (a != 0) {
        sd.step1 = "\\text{1) Ecuación característica:}"
                + formatCoefficient(a, true, false) + "m^2"
                + formatCoefficient(b, false, false) + "m"
                + formatCoefficient(c, false, true)
                + " = 0";
    } else {
        sd.step1 = "\\text{1) Ecuación de primer orden:}"
                + formatCoefficient(b, true, false) + "m"
                + formatCoefficient(c, false, true)
                + " = 0";
    }

    // ===========================================================
    // 2) Soluciones m1, m2 (solo si es de 2º orden)
    // ===========================================================
    if (a != 0 && roots != null) {
        String m1 = formatRootLatex(roots.getFirst());
        String m2 = formatRootLatex(roots.getSecond());
        sd.step2 = "\\text{2) Soluciones de la característica:}"
                + "m_1 = " + m1 + ",\\quad m_2 = " + m2;
    } else {
        int gcd = mathUtils.gcd(b, c);
        int bSim = b / gcd;
        int cSim = -c / gcd;

        if (bSim < 0) { bSim = -bSim; cSim = -cSim; }

        String mValue;
        if (bSim == 1) {
            mValue = cSim + "";
        } else {
            mValue = "\\frac{" + cSim + "}{" + bSim + "}";
        }
        sd.step2 = "\\text{2) Solución de la característica:}m = " + mValue;
    }

    // ===========================================================
    // 3) y1, y2 (o solo y1 si es 1er orden)
    // ===========================================================
    String[] ys = (a != 0)
            ? buildY1Y2Latex(ec, roots)
            : new String[]{buildY1FirstOrderLatex(b, c), ""};

    if (a != 0) {
        sd.step3 = "\\text{3) Soluciones de la homogénea:}"
                + "y_1 = " + ys[0] + "y_2 = " + ys[1];
    } else {
        sd.step3 = "\\text{3) Solución de la homogénea:}y_1 = " + ys[0];
    }

    // ===========================================================
    // 4) Solución general
    // ===========================================================
    if (a != 0) {
        sd.step4 = "\\text{4) Solución general:}"
                + "y_c = C_1" + formatMultiplication(ys[0])
                + " + C_2" + formatMultiplication(ys[1]);
    } else {
        sd.step4 = "\\text{4) Solución general:}"
                + "y_c = C" + formatMultiplication(ys[0]);
    }

    return sd;
}


    /**
     * Formatea coeficientes para LaTeX (simplifica 1, -1, 0)
     * @param coef coeficiente numérico
     * @param isFirst true si es el primer término
     * @return String formateado para LaTeX
     */
    /**
 * Formatea coeficientes para LaTeX asegurando signos y espacios correctos.
 * Siempre devuelve algo como:
 *   "" , "+ ", "- ", "+ k ", "- k "
 */
private String formatCoefficient(int coef, boolean isFirst, boolean isLast) {

    // coef = 0 → evitar concatenación tipo "m^2m"
    if (coef == 0) {
        return isFirst ? "" : " ";
    }

    // Primer término (a·m^2)
    if (isFirst) {
        if (coef == 1)  return "";
        if (coef == -1) return "-";
        return coef + "";
    }

    // Último término (c)
    if (isLast) {
        if (coef > 0)  return " + " + coef;
        return " - " + Math.abs(coef);
    }

    // Término intermedio (b·m)
    if (coef == 1)  return " + ";
    if (coef == -1) return " - ";
    if (coef > 0)   return " + " + coef;
    return " - " + Math.abs(coef);
}



    /**
     * Formatea una raíz compleja para LaTeX (simplifica 0, 1, -1)
     */
    private String formatRootLatex(Complex c) {
        String a = c.getAlpha();
        String b = c.getBeta();
        
        // Solo parte real
        if ("0".equals(b) || "".equals(b)) {
            if ("0".equals(a)) return "0";
            return a;
        }
        
        // Solo parte imaginaria
        if ("0".equals(a) || "".equals(a)) {
            if ("1".equals(b)) return "i";
            if ("-1".equals(b)) return "-i";
            return b + "i";
        }
        
        // Ambas partes
        String imagPart;
        if ("1".equals(b)) {
            imagPart = "i";
        } else if ("-1".equals(b)) {
            imagPart = "i";
            return a + " - " + imagPart;
        } else {
            imagPart = b + "i";
        }
        
        if (b.startsWith("-")) {
            return a + " - " + imagPart.substring(1);
        } else {
            return a + " + " + imagPart;
        }
    }

    /**
     * Construye y1, y2 en formato LaTeX para segundo orden
     */
    private String[] buildY1Y2Latex(ecCuadraticas ec, Pair<Complex, Complex> roots) {
        int disc = ec.discriminante();
        Complex r1 = roots.getFirst();
        Complex r2 = roots.getSecond();
        String alpha = r1.getAlpha();
        String beta = r1.getBeta();
        String alpha2 = r2.getAlpha();

        if (disc > 0) {
            String y1 = ("0".equals(alpha)) ? "1" : buildExpLatex(alpha);
            String y2 = ("0".equals(alpha2)) ? "1" : buildExpLatex(alpha2);
            return new String[]{y1, y2};
        } else if (disc == 0) {
            String base = ("0".equals(alpha)) ? "1" : buildExpLatex(alpha);
            String y1 = base;
            String y2 = ("1".equals(base)) ? "x" : "x" + base;
            return new String[]{y1, y2};
        } else { // disc < 0
            String cosine = "\\cos(" + formatInnerExp(beta) + "x)";
            String sine = "\\sin(" + formatInnerExp(beta) + "x)";
            
            if ("0".equals(alpha)) {
                return new String[]{cosine, sine};
            } else {
                String expPart = buildExpLatex(alpha);
                return new String[]{expPart + cosine, expPart + sine};
            }
        }
    }

    /**
     * Construye e^{...x} simplificando 1, -1, 0
     */
    private String buildExpLatex(String coef) {
        if ("0".equals(coef)) return "1";
        if ("1".equals(coef)) return "e^{x}";
        if ("-1".equals(coef)) return "e^{-x}";
        
        // Si es fracción (contiene \frac)
        if (coef.contains("\\frac")) {
            return "e^{" + coef + "x}";
        }
        
        return "e^{" + coef + "x}";
    }

    /**
     * Formatea el exponente interno (para cos/sin)
     */
    private String formatInnerExp(String coef) {
        if ("1".equals(coef)) return "";
        if ("-1".equals(coef)) return "-";
        return coef;
    }

    /**
     * y1 en formato LaTeX para primer orden
     */
    private String buildY1FirstOrderLatex(int b, int c) {
        int gcd = mathUtils.gcd(b, c);
        b /= gcd;
        c /= gcd;
        c = -c;
        if (b < 0) { b = -b; c = -c; }
        
        String coef;
        if (b == 1 && c == 1) {
            coef = "1";
        } else if (c == 1) {
            coef = "\\frac{1}{" + b + "}";
        } else if (b == 1) {
            coef = c + "";
        } else {
            coef = "\\frac{" + c + "}{" + b + "}";
        }
        
        if ("0".equals(coef)) return "1";
        if ("1".equals(coef)) return "e^{x}";
        if ("-1".equals(coef)) return "e^{-x}";
        
        return "e^{" + coef + "x}";
    }

    /**
     * Formatea la multiplicación con constantes (evita C1·1)
     */
    private String formatMultiplication(String term) {
        if ("1".equals(term)) return "";
        return term;
    }

    // ============= MÉTODOS CON AGREGACIÓN EXPLÍCITA =============
    
    /**
     * Resuelve ecuación diferencial de primer orden
     * Demuestra AGREGACIÓN: recibe un objeto ecCuadraticas agregado
     * 
     * @param ec objeto ecCuadraticas agregado que contiene los coeficientes
     * @return String con la solución en formato LaTeX
     */
    private String firstOrderEc(ecCuadraticas ec) {
        // AGREGACIÓN: Usamos el objeto ec agregado
        return firstOrderEc(ec.getB(), ec.getC());
    }

    /**
     * Resuelve ecuación diferencial de primer orden
     * Versión sobrecargada que recibe parámetros primitivos
     * 
     * @param b coeficiente de y'
     * @param c coeficiente de y
     * @return String con la solución en formato LaTeX
     */
    private String firstOrderEc(int b, int c) {
        int gcd = mathUtils.gcd(b, c);
        b /= gcd; 
        c /= gcd;
        
        c=-c;
        // Normalización de signos
        if (b < 0) {
            b = -b;
            c = -c;
        }

        String strSol,y;

        if (b == 1 && c == 1) {
            strSol = "1";
        } 
        else if (c == 1) {
            strSol = "\\frac{1}{" + b + "}";
        } 
        else if (b == 1) {
            strSol =  c + "";
        } 
        else {
            strSol = "\\frac{" + c + "}{" + b + "}";
        }
        
        if("1".equals(strSol)) strSol="";
        if("-1".equals(strSol)) strSol="-";
        
        y="Y_c=Ce^{"+strSol+"x}";

        return y;
    }

    /**
     * Resuelve ecuación diferencial de segundo orden
     * Demuestra AGREGACIÓN: recibe un objeto ecCuadraticas agregado
     * 
     * @param ec objeto ecCuadraticas agregado que contiene los coeficientes
     * @return String con la solución en formato LaTeX
     */
    private String secondOrderEc(ecCuadraticas ec) {
        // AGREGACIÓN: Usamos el objeto ec agregado
        return secondOrderEc(ec.getA(), ec.getB(), ec.getC());
    }

    /**
 * Resuelve ecuación diferencial de segundo orden.
 * Versión sobrecargada que recibe parámetros primitivos.
 * Demuestra AGREGACIÓN: crea y utiliza objetos Pair<Complex, Complex>
 *
 * @param a coeficiente de y''
 * @param b coeficiente de y'
 * @param c coeficiente de y
 * @return String con la solución en formato LaTeX
 */
private String secondOrderEc(int a, int b, int c) {

    ecCuadraticas ecCaracteristica = new ecCuadraticas(a, b, c);

    Pair<Complex, Complex> roots = ecCaracteristica.getRoots();
    this.raicesActuales = roots;
    this.raizCompleja1 = roots.getFirst();
    this.raizCompleja2 = roots.getSecond();

    int disc = ecCaracteristica.discriminante();

    // Extraemos partes reales e imaginarias
    String alpha  = normalizeCoef(raizCompleja1.getAlpha());
    String beta   = normalizeCoef(raizCompleja1.getBeta());
    String alpha2 = normalizeCoef(raizCompleja2.getAlpha());

    String y1, y2;

    if (disc > 0) {  
        // Raíces reales distintas
        y1 = buildRealExp(alpha);
        y2 = buildRealExp(alpha2);

    } else if (disc == 0) {  
        // Raíz real doble
        if ("0".equals(alpha)) {
            y1 = "";
            y2 = "x";
        } else {
            y1 = "e^{" + alpha + "x}";
            y2 = "x" + y1;
        }

    } else {  
        // Raíces complejas
        if ("0".equals(alpha)) {
            y1 = "\\cos(" + beta + "x)";
            y2 = "\\sin(" + beta + "x)";
        } else {
            y1 = "e^{" + alpha + "x}\\cos(" + beta + "x)";
            y2 = "e^{" + alpha + "x}\\sin(" + beta + "x)";
        }
    }

    return "Y_c = C_1" + y1 + " + C_2" + y2;
}

/* ----------------------------------------------------------
   FUNCIONES AUXILIARES
   ---------------------------------------------------------- */

/** Normaliza coeficientes tipo "1", "-1", etc. */
private String normalizeCoef(String v) {
    if (v == null) return "0";
    switch (v) {
        case "1":  return "";
        case "-1": return "-";
        default:   return v;
    }
}

/** Construye expresión e^{αx} pero omite si α=0 */
private String buildRealExp(String alpha) {
    return "0".equals(alpha) ? "" : "e^{" + alpha + "x}";
}


    
    // ============= GETTERS PARA ACCESO A OBJETOS AGREGADOS =============
    
    /**
     * Obtiene la ecuación actual agregada
     * @return objeto ecCuadraticas agregado
     */
    public ecCuadraticas getEcuacionActual() {
        return this.ecuacionActual;
    }
    
    /**
     * Obtiene las raíces actuales agregadas
     * @return objeto Pair<Complex, Complex> con las raíces
     */
    public Pair<Complex, Complex> getRaicesActuales() {
        return this.raicesActuales;
    }
    
    /**
     * Obtiene la primera raíz agregada
     * @return objeto Complex con la primera raíz
     */
    public Complex getRaizCompleja1() {
        return this.raizCompleja1;
    }
    
    /**
     * Obtiene la segunda raíz agregada
     * @return objeto Complex con la segunda raíz
     */
    public Complex getRaizCompleja2() {
        return this.raizCompleja2;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmSolver().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSolve;
    private javax.swing.JButton btnSteps;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblD2y;
    private javax.swing.JLabel lblDy;
    private javax.swing.JLabel lblSol;
    private javax.swing.JLabel lblSolTitle;
    private javax.swing.JLabel lblY;
    private javax.swing.JPanel panSolution;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    // End of variables declaration//GEN-END:variables
}
